name: Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          curl -LO https://github.com/sunshineplan/capital-flows/releases/latest/download/run
          sudo chmod +x run
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          ./run -mongo ${{ secrets.MONGO }} -token ${{ github.token }} -repo $GITHUB_REPOSITORY -path data
