name: Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
    
      - name: Run
        run: |
          curl -LO https://github.com/sunshineplan/capital-flows/releases/latest/download/run
          sudo chmod +x run
          ./run -mongo ${{ secrets.MONGO }} -path repo/data -commit
          cd repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "$(TZ=PRC date +'%Y-%m-%d')" && git push
          cd ..
          ./run -mongo ${{ secrets.MONGO }} -delete
